name: Bump reusable workflows version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bump-version:
    name: Bump version
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout the code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # 1.75.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        WITH_V: true
