name: Build and test npm package with PostgreSQL service

on:
  workflow_call:
    inputs:
      node:
        description: 'JSON array of Node.js versions and parameters'
        required: false
        type: string
        default: '[{"version": "24", "tests": true, "lint": true}]'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        node: ${{ fromJson(inputs.node)}}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js ${{ matrix.node.version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node.version }}
  
      - name: Install Dependencies
        run: npm ci
  
      - name: Run lint
        if: ${{ fromJson(matrix.node.lint) }}
        run: npm run lint
  
      - name: Run tests
        if: ${{ fromJson(matrix.node.tests) }}
        run: npm run test
