name: Build and test npm package

on:
  workflow_call:
    inputs:
      run_tests:
        description: 'Run tests'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: [16.x]
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: NPM
          uses: 'flowforge/github-actions-workflows/actions/npm_test@main'
          with:
            node_version: ${{ matrix.node-version }}
            run_tests: ${{ inputs.run_tests }}
