name: Build and test npm package

on:
  workflow_call:
    inputs:
      node:
        description: 'JSON array of Node.js versions and parameters'
        required: false
        type: string
        default: '[{"version": "20", "tests": true, "lint": true}]'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          node: ${{ fromJson(inputs.node)}}
    name: Build on ${{ matrix.node.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js ${{ matrix.node.version}}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node.version }}
  
      - name: Install Dependencies
        run: npm ci
  
      - name: Run lint
        if: ${{ fromJson(matrix.node.lint) }}
        run: npm run lint
  
      - name: Run tests
        if: ${{ fromJson(matrix.node.tests) }}
        run: npm run test
