name: Build and test npm package

on:
  workflow_call:
    inputs:
      run_tests:
        description: 'Run tests'
        required: false
        type: boolean
        default: false
      node:
        description: 'JSON array of Node.js versions and parameters'
        required: false
        type: string
        default: '[{"version": "18", "test": true, "lint": true}]'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          node-version: ${{ fromJson(inputs.node)}}
    name: Build on ${{ matrix.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
  
      - name: Install Dependencies
        run: npm ci
  
      - name: Run lint
        if: ${{ fromJson(matrix.lint) }}
        run: npm run lint
  
      - name: Run tests
        if: ${{ fromJson(matrix.test) }}
        run: npm run test
