name: Build and test npm package

on:
  workflow_call:
    inputs:
      run_tests:
        description: 'Run tests'
        required: false
        type: boolean
        default: false
      node_version:
        description: 'Node.js version'
        required: false
        type: string
        default: '["18.x"]'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: ${{ fromJson(inputs.node_version)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
  
      - name: Install Dependencies
        run: npm ci
  
      - name: Run lint
        run: npm run lint
  
      - name: Run tests
        if: ${{ fromJson(inputs.run_tests)}}
        run: npm run test
