name: Merge multiplatform images

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the image to build'
        required: true
        type: string
      image_tag_prefix:
        description: 'Prefix of the image tag'
        required: false
        type: string
      architecture_suffixes:
        description: 'Architecture suffixes'
        type: string
        required: false
        default: |
          -linux-amd64
          -linux-arm64
    secrets:
      temporary_registry_token:
        description: 'GitHub token'
        required: true
    outputs:
      image:
        description: 'Full image tag'
        value: ${{ jobs.merge.outputs.image }}

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      image: ${{ steps.set_outputs.outputs.image }}
    
    steps:
      - name: Set required environmental variables
        run: |
          echo "repository_owner_lower=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to temporary registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.temporary_registry_token}}

      - uses: int128/docker-manifest-create-action@736aaa0f6ae97b2fb7f43e8dcef3ab47a02ea96e # v2.8.0
        name: Merge and push
        with:
          tags: ghcr.io/${{ env.repository_owner_lower }}/${{ inputs.image_name }}:${{ inputs.image_tag_prefix }}main
          suffixes: ${{ inputs.architecture_suffixes}}
      
      - name: Prune old images
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with: 
          package-name: ${{ inputs.image_name }}
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: 'true'

      - name: Set workflow outputs
        id: set_outputs
        run: |
          echo "image=ghcr.io/${{ env.repository_owner_lower }}/${{ inputs.image_name }}:${{ inputs.image_tag_prefix }}main" >> $GITHUB_OUTPUT
  