name: Merge multiplatform images

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the image to build'
        required: true
        type: string
      architecture_suffixes:
        description: 'Architecture suffixes'
        type: string
        required: false
        default: |
          -linux-amd64
          -linux-arm64
    secrets:
      temporary_registry_token:
        description: 'GitHub token'
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      packages: delete
      contents: read
    steps:
      - name: Login to temporary registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.temporary_registry_token}}

      - uses: int128/docker-manifest-create-action@v1
        name: Merge and push
        with:
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:main
          suffixes: ${{ inputs.architecture_suffixes}}
      
      - name: Prune old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: main
          cut-off: two hours ago UTC
          timestamp-to-use: updated_at
          account-type: org
          org-name: ${{ github.repository_owner }}
          keep-at-least: 1
          skip-tags: main
          token: ${{ secrets.temporary_registry_token }}
