name: Add new issues to the Relevant Boards

on:
  workflow_call:
    secrets:
      app-client-id:
        required: true
      app-private-key:
        required: true

jobs:
  add-to-project-board:
    name: Add issue to project
    if: | 
      github.repository != 'FlowFuse/website' &&
      github.repository != 'FlowFuse/node-red-dashboard'
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.app-client-id }}
          private-key: ${{ secrets.app-private-key }}
          owner: ${{ github.repository_owner }}
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/FlowFuse/projects/3
          github-token: ${{ steps.generate_token.outputs.token }}

  add-to-artwork-board:
    name: Add art requests to the Artwork board
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.app-client-id }}
          private-key: ${{ secrets.app-private-key }}
          owner: ${{ github.repository_owner }}
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          labeled: design, artwork
          label-operator: AND
          project-url: https://github.com/orgs/FlowFuse/projects/10
          github-token: ${{ steps.generate_token.outputs.token }}
  
  add-to-dashboard-backlog:
    name: Add issues to the Dashboard Backlog project board
    if: github.repository == 'FlowFuse/node-red-dashboard'
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.app-client-id }}
          private-key: ${{ secrets.app-private-key }}
          owner: ${{ github.repository_owner }}
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          labeled: needs-triage
          project-url: https://github.com/orgs/FlowFuse/projects/15
          github-token: ${{ steps.generate_token.outputs.token }}
