name: Codebase SAST Scan
on:
  workflow_call:
    inputs:
      fail_on_severity:
        description: 'Fail the scan if vulnerabilities of this severity or higher are found. Valid values: CRITICAL, HIGH, MEDIUM, LOW, UNKNOWN, NONE'
        required: false
        type: string
        default: 'NONE'
      upload_results_to_ghas:
        description: 'Upload the scan results to GitHub Advanced Security'
        required: false
        type: boolean
        default: true
      upload_results_to_pr:
        description: 'Upload the scan results as a comment on the pull request'
        required: false
        type: boolean
        default: false

jobs:
  codebase-scan:
    name: Codebase Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
      pull-requests: write
      checks: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Cache vulnerability database
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .cache/trivy
          key: ${{ runner.os }}-trivy-db-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-trivy-db-

      - name: Perform SAST scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: '.github/trivy.yaml'
          output: 'trivy-results.sarif'
          version: 'v0.69.2' # https://github.com/aquasecurity/trivy-action/issues/512
        env:
          TRIVY_FAIL_ON_SEVERITY: ${{ inputs.fail_on_severity }}

      - name: Upload scan results to GitHub
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        if: ${{ inputs.upload_results_to_ghas }}
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-sast'

      - name: Upload scan results to PR
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        if: ${{ inputs.upload_results_to_pr && github.event_name == 'pull_request' }}
        with: 
          header: '## SAST Scan Results'
          path: 'trivy-results.sarif'
